//
// Created by Adrian Welcker on 2019-07-26.
//

#ifndef STELLARIS_STAT_VIEWER_EXTRACT_GAMESTATE_H
#define STELLARIS_STAT_VIEWER_EXTRACT_GAMESTATE_H

#endif //STELLARIS_STAT_VIEWER_EXTRACT_GAMESTATE_H
